[package]
name = "fox-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fox-bytecode = { path = "../fox-bytecode" }
pixels = "0.11.0"
winit = "0.27.5"
